services:
  - type: web
    name: aluminium-imputer-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3.10 python3.10-venv python3.10-distutils
      update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
      python3 -m venv .venv
      . .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: .venv/bin/uvicorn main_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
